services:
  db:
    image: postgres:13
    container_name: restaurant_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: .
    container_name: restaurant_app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/restaurant
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network: